### Registration
POST localhost:8080/auth/registration
Content-Type: application/json
Accept-Language: UZ

{
  "name": "Akromjonnn255",
  "username": "maxamadqulovilkhomjon@gmail.com",
  "password": "12345"
}

### Registration Verification
GET http://localhost:8080/auth/registration/verification/{profileId}
Accept-Language: UZ

### Login
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "username": "maxamadqulovilkhomjon@gmail.com",
  "password": "12345"
}