### Registration
POST localhost:8080/auth/registration
Content-Type: application/json
Accept-Language: RU

{
  "name": "Akromjonnn255",
  "username": "+998502229427",
  "password": "12345"
}

### Registration Verification
GET http://localhost:8080/auth/registration/email-verification/{profileId}


### Registration with sms
POST https:// localhost:8080/auth/registration/sms-verification
Accept-Language: UZ

{
    "phone": +998
}

### Login
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: UZ

{
  "username": "maxamadqulovilkhomjon@gmail.com",
  "password": "12345"
}