
### Post
POST localhost:8080/post/create-post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXhhbWFkcXVsb3ZpbGtob21qb25AZ21haWwuY29tIiwicm9sZXMiOiJST0xFX1VTRVIiLCJpZCI6IjM1IiwidXNlcm5hbWUiOiJtYXhhbWFkcXVsb3ZpbGtob21qb25AZ21haWwuY29tIiwiaWF0IjoxNzY0ODgyOTcyLCJleHAiOjE3NjQ4ODMyNzJ9.IuzkGJsZP0wshLQ5GxQYfYVbiOVoI_o_Irj4WhnTDl6jbv6tmzBMJc4fvwxbTEMPXMO5gdxdVzQE1yJclR7Eug

